ITR_CATALOG = [
  # CIVIL
  {"file":'ITR-Civil-Building-Footing-Concrete-Blocks.docx',"title":'Building Footing Concrete Blocks',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Capping-Construction.docx',"title":'Capping Construction',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Clear-Grub-Topsoil-Removal.docx',"title":'Clear Grub Topsoil Removal',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Concrete-Pre-Pour.docx',"title":'Concrete Pre-Pour',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Culverts-Installation.docx',"title":'Culverts Installation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Drainage.docx',"title":'Drainage',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Earthworks-Excavation.docx',"title":'Earthworks Excavation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Embankment-Construction.docx',"title":'Embankment Construction',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Embankment-Foundation-Preparation.docx',"title":'Embankment Foundation Preparation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Fencing.docx',"title":'Fencing',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Foundation.docx',"title":'Foundation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-In-Situ-Concrete.docx',"title":'In Situ Concrete',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Structural-Backfill.docx',"title":'Structural Backfill',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Subgrade-Preparation.docx',"title":'Subgrade Preparation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Trenching-and-Bedding.docx',"title":'Trenching and Bedding',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Turkeys-Nest.docx',"title":'Turkeys Nest',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Two-Coat-Seal-Installation.docx',"title":'Two Coat Seal Installation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Underground-Conduit-Installation.docx',"title":'Underground Conduit Installation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Civil-Wearing-Course-Preparation.docx',"title":'Wearing Course Preparation',"cat":'civil',"fmt":'docx',"stages":[5],"roles":['PM', 'Engineer', 'Quality', 'Scheduler']},
  # STRUCTURAL
  {"file":'ITR-Structural-Bins-Chutes-and-Hoppers.docx',"title":'Bins, Chutes and Hoppers',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Bolt-Torque.docx',"title":'Bolt Torque',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Buildings-Cladded.docx',"title":'Buildings (Cladded)',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Builiding-Stick-Build.docx',"title":'Builiding (Stick Build)',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Concrete-Precast-Panel-Installation.docx',"title":'Concrete Precast Panel Installation',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Conveyor-Head-Chute.docx',"title":'Conveyor Head Chute',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Conveyor-Module-Installation.docx',"title":'Conveyor Module Installation',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Conveyor-Stick-Build.docx',"title":'Conveyor Stick Build',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Cranes-and-Hoists.docx',"title":'Cranes and Hoists',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Foundation.docx',"title":'Foundation',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Gridmesh.docx',"title":'Gridmesh',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Grout.docx',"title":'Grout',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Handrails.docx',"title":'Handrails',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Hood.docx',"title":'Hood',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Isolation-Gate.docx',"title":'Isolation Gate',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Light-Pole.docx',"title":'Light Pole',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-MP-Platform-Inspection-Form.docx',"title":'MP Platform Inspection Form',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Maintenance-Platform.docx',"title":'Maintenance Platform',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Module-Instalation.docx',"title":'Module Instalation',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Pressure-Vessel.docx',"title":'Pressure Vessel',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Stairs-and-Ladders.docx',"title":'Stairs and Ladders',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Steel-Erection.docx',"title":'Steel Erection',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Surface-Treatment.docx',"title":'Surface Treatment',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-Tramp-Metal-Magnet.docx',"title":'Tramp Metal Magnet',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-andrailing.docx',"title":'andrailing',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-ank-Installation.docx',"title":'ank Installation',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-ins-and-Chutes.docx',"title":'ins and Chutes',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-ladding.docx',"title":'ladding',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-odule-Placement.docx',"title":'odule Placement',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-rane-Rails.docx',"title":'rane Rails',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-ridmesh-Installation.docx',"title":'ridmesh Installation',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-tairs-and-Ladders.docx',"title":'tairs and Ladders',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-tructural-Steel-Installation.docx',"title":'tructural Steel Installation',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  {"file":'ITR-Structural-urface-Treatment.docx',"title":'urface Treatment',"cat":'structural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality', 'Scheduler']},
  # MECHANICAL
  {"file":'ITR-Mechanical--Belt.docx',"title":'-Belt',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Accumulator.docx',"title":'Accumulator',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Activator.docx',"title":'Activator',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Actuator.docx',"title":'Actuator',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Agitator.docx',"title":'Agitator',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Air-Dryer.docx',"title":'Air Dryer',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Air-Receiver.docx',"title":'Air Receiver',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Apron-Feeder.docx',"title":'Apron Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Backfill-for-Utility-Trench.docx',"title":'Backfill for Utility Trench',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Bearing.docx',"title":'Bearing',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Belt-Feeder.docx',"title":'Belt Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Belt-Plough.docx',"title":'Belt Plough',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Belt-Reeler.docx',"title":'Belt Reeler',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Belt-Scraper.docx',"title":'Belt Scraper',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Blower.docx',"title":'Blower',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Boom-Gate.docx',"title":'Boom Gate',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Bore.docx',"title":'Bore',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Bore-Headworks.docx',"title":'Bore Headworks',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Brake.docx',"title":'Brake',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Carousel.docx',"title":'Carousel',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Compressor.docx',"title":'Compressor',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Conveyor.docx',"title":'Conveyor',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Crane.docx',"title":'Crane',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Cutter.docx',"title":'Cutter',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Distribution-Box-Slurry.docx',"title":'Distribution Box (Slurry)',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Drive-Assembly.docx',"title":'Drive Assembly',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Drive-Coupling.docx',"title":'Drive Coupling',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Dust-Collector.docx',"title":'Dust Collector',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Dust-Suppression.docx',"title":'Dust Suppression',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Earthworks.docx',"title":'Earthworks',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Fail-Safe-Pump-Station.docx',"title":'Fail Safe Pump Station',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Fan.docx',"title":'Fan',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Filter.docx',"title":'Filter',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Floating-Return-Belt-Plough.docx',"title":'Floating Return Belt Plough',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Fluid-Coupling.docx',"title":'Fluid Coupling',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Gate.docx',"title":'Gate',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Gear-Box.docx',"title":'Gear Box',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Generator.docx',"title":'Generator',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Head-Chute-Adjustable-Rock-Box.docx',"title":'Head Chute Adjustable Rock Box',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Heat-Exchanger.docx',"title":'Heat Exchanger',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Heat-Exchanger-Cooler.docx',"title":'Heat Exchanger Cooler',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Hoist.docx',"title":'Hoist',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Hydraulic-pack.docx',"title":'Hydraulic pack',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Idler.docx',"title":'Idler',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Impact-Plate.docx',"title":'Impact Plate',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Inching-Drive.docx',"title":'Inching Drive',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Insert-Chute.docx',"title":'Insert Chute',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Isolation-Gate.docx',"title":'Isolation Gate',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Launder.docx',"title":'Launder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Lube-System.docx',"title":'Lube System',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Lubrication-System.docx',"title":'Lubrication System',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Magnet.docx',"title":'Magnet',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Monorail.docx',"title":'Monorail',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Motor-Diesel.docx',"title":'Motor Diesel',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Motor-Hydraulic.docx',"title":'Motor Hydraulic',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-On-line-On-stream-analyser.docx',"title":'On-line On-stream analyser',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pit-Sump-Pump-Diesel.docx',"title":'Pit Sump Pump (Diesel)',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pulley.docx',"title":'Pulley',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pulleys.docx',"title":'Pulleys',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pump.docx',"title":'Pump',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pump-Bore-Pump.docx',"title":'Pump Bore Pump',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pump-Process-Slurry.docx',"title":'Pump Process Slurry',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pump-Raw-Water.docx',"title":'Pump Raw Water',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Pump-Sump-Pump.docx',"title":'Pump Sump Pump',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Rake.docx',"title":'Rake',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Rotary-Sample-Splitter.docx',"title":'Rotary Sample Splitter',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Rotary-sample-collector.docx',"title":'Rotary sample collector',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Sample-Crusher.docx',"title":'Sample Crusher',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Sample-Feeder.docx',"title":'Sample Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Screw-feeder.docx',"title":'Screw feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Scrubber.docx',"title":'Scrubber',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Security-Gate.docx',"title":'Security Gate',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Sizer.docx',"title":'Sizer',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Skirt-Lifter.docx',"title":'Skirt Lifter',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Surge-Belt-plough.docx',"title":'Surge Belt plough',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Take-Up.docx',"title":'Take Up',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Tank.docx',"title":'Tank',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Tooth-Removal-Machine-Sizer.docx',"title":'Tooth Removal Machine (Sizer)',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Travel-Drive.docx',"title":'Travel Drive',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Trenching-and-Backfill.docx',"title":'Trenching and Backfill',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-Vibrating-Screen.docx',"title":'Vibrating Screen',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ake-Up-Winch.docx',"title":'ake Up Winch',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ample-Carousel.docx',"title":'ample Carousel',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ample-Station-Belt-Feeder.docx',"title":'ample Station Belt Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ample-Station-Screen.docx',"title":'ample Station Screen',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ample-Station-Vibrating-Feeder.docx',"title":'ample Station Vibrating Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ample-Station-Weigh-Bins.docx',"title":'ample Station Weigh Bins',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-dlers.docx',"title":'dlers',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-echanical-Coupling-Flexible.docx',"title":'echanical Coupling - Flexible',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-echanical-Coupling-Rigid.docx',"title":'echanical Coupling - Rigid',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-econdary-Sample-Cutter.docx',"title":'econdary Sample Cutter',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-eightometer.docx',"title":'eightometer',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-elt-Feeder.docx',"title":'elt Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-elt-Plough.docx',"title":'elt Plough',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-elt-Scraper.docx',"title":'elt Scraper',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-elt-Splicing.docx',"title":'elt Splicing',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-eneral-Mechanical.docx',"title":'eneral Mechanical',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-entrifugal-Pump.docx',"title":'entrifugal Pump',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ertical-Gravity-Take-Up.docx',"title":'ertical Gravity Take Up',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-etal-Detector.docx',"title":'etal Detector',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ezin-Cutter.docx',"title":'ezin Cutter',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-hiller.docx',"title":'hiller',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-huttling-Splitter-Chute.docx',"title":'huttling Splitter Chute',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ibrating-Feeder.docx',"title":'ibrating Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ibrating-Grizzly.docx',"title":'ibrating Grizzly',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ibrating-Screen.docx',"title":'ibrating Screen',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ile-Cap-Install.docx',"title":'ile Cap Install',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-iverter-Gate.docx',"title":'iverter Gate',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ixed-Screw-Take-Up.docx',"title":'ixed Screw Take Up',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-izer.docx',"title":'izer',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-lectrical-Overhead-Crane.docx',"title":'lectrical Overhead Crane',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-luid-Coupling.docx',"title":'luid Coupling',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-neumatic-System.docx',"title":'neumatic System',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-olt-Tensioning.docx',"title":'olt Tensioning',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-olt-Toruqe-Sheet-Mechanical.docx',"title":'olt Toruqe Sheet Mechanical',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ompaction.docx',"title":'ompaction',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-oncrete-Pre-and-Post-Pour.docx',"title":'oncrete Pre and Post Pour',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-onveyor-Installation.docx',"title":'onveyor Installation',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-orizontal-Gravity-Take-Up.docx',"title":'orizontal Gravity Take Up',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-pron-Feeder.docx',"title":'pron Feeder',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-quipment-Inspection-On-Site.docx',"title":'quipment Inspection On-Site',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ramp-Metal-Magnet.docx',"title":'ramp Metal Magnet',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-re-Cast-Concrete-Pre-and-Post-Pour.docx',"title":'re-Cast Concrete Pre and Post Pour',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-re-Cast-Panel-Installation.docx',"title":'re-Cast Panel Installation',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ressure-Vessel.docx',"title":'ressure Vessel',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-rimary-Sample-Cutter.docx',"title":'rimary Sample Cutter',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ripper-Shuttle.docx',"title":'ripper & Shuttle',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-rives.docx',"title":'rives',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-routing-Cementitious.docx',"title":'routing - Cementitious',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-routing-Epoxy.docx',"title":'routing - Epoxy',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ulleys.docx',"title":'ulleys',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ust-Collector.docx',"title":'ust Collector',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ust-Extraction-System.docx',"title":'ust Extraction System',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ydraulic-Disc-Brake.docx',"title":'ydraulic Disc Brake',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ydraulic-Lube-System.docx',"title":'ydraulic Lube System',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ydraulic-Motor-Power-Pack.docx',"title":'ydraulic Motor & Power Pack',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Mechanical-ydraulic-Take-Up.docx',"title":'ydraulic Take Up',"cat":'mechanical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  # PIPING
  {"file":'ITR-Piping-Expansion-Joint.docx',"title":'Expansion Joint',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Eye-Wash-Safety-Shower-Station.docx',"title":'Eye Wash Safety Shower Station',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Fire-Hose-Reel.docx',"title":'Fire Hose Reel',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Fire-Hydrant.docx',"title":'Fire Hydrant',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-12-Bolt.docx',"title":'Flange Torque Sheet (12 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-16-Bolt.docx',"title":'Flange Torque Sheet (16 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-20-Bolt.docx',"title":'Flange Torque Sheet (20 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-24-Bolt.docx',"title":'Flange Torque Sheet (24 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-28-Bolt.docx',"title":'Flange Torque Sheet (28 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-32-Bolt.docx',"title":'Flange Torque Sheet (32 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-36-Bolt.docx',"title":'Flange Torque Sheet (36 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-4-Bolt.docx',"title":'Flange Torque Sheet (4 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-40-Bolt.docx',"title":'Flange Torque Sheet (40 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-44-Bolt.docx',"title":'Flange Torque Sheet (44 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Flange-Torque-Sheet-8-Bolt.docx',"title":'Flange Torque Sheet (8 Bolt)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Grooved-Coupling.docx',"title":'Grooved Coupling',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-HDPE-Welded-and-Bolted-Piping.docx',"title":'HDPE Welded and Bolted Piping',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Hose-Reel.docx',"title":'Hose Reel',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Hydraulic-Flushing.docx',"title":'Hydraulic Flushing',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Hydro-Test.docx',"title":'Hydro Test',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-In-Service-Leak-Test.docx',"title":'In-Service Leak Test',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Instrument-Air.docx',"title":'Instrument Air',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Load-Test.docx',"title":'Load Test',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-No-Load-Test.docx',"title":'No Load Test',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Orifice-Plate.docx',"title":'Orifice Plate',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Pipe-Compression.docx',"title":'Pipe Compression',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Pipe-Instrument.docx',"title":'Pipe Instrument',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Pipe-PVC.docx',"title":'Pipe PVC',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Pipe-Steel-Bolted-Welded-Threaded.docx',"title":'Pipe Steel (Bolted, Welded Threaded)',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Pipe-Vendor-Assembly.docx',"title":'Pipe Vendor Assembly',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Potable-Water-Flushing-and-Disinfection.docx',"title":'Potable Water Flushing and Disinfection',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Spray-Bar-Assembly.docx',"title":'Spray Bar Assembly',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Valve-General.doc',"title":'Valve General',"cat":'piping',"fmt":'doc',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Valve-OnOff-Actuated-Modulating.docx',"title":'Valve OnOff, Actuated Modulating',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Valve-Pressure-Reducing.docx',"title":'Valve Pressure Reducing',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Valve-Safety-Relief.docx',"title":'Valve Safety Relief',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Valve-Solenoid.docx',"title":'Valve Solenoid',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-Water-Cannon.docx',"title":'Water Cannon',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-elt-Reeler.docx',"title":'elt Reeler',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-elt-Wash.docx',"title":'elt Wash',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-hreaded-Piping.docx',"title":'hreaded Piping',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-ipe-Flushing.docx',"title":'ipe Flushing',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-ipe-Installation-PVC.docx',"title":'ipe Installation - PVC',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-iping-Preparation.docx',"title":'iping Preparation',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-iping-Pressfit.docx',"title":'iping Pressfit',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-iping-Reinstatement.docx',"title":'iping Reinstatement',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-12-Bolt.docx',"title":'lange Torque Sheet - 12 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-16-Bolt.docx',"title":'lange Torque Sheet - 16 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-20-Bolt.docx',"title":'lange Torque Sheet - 20 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-24-Bolt.docx',"title":'lange Torque Sheet - 24 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-28-Bolt.docx',"title":'lange Torque Sheet - 28 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-32-Bolt.docx',"title":'lange Torque Sheet - 32 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-36-Bolt.docx',"title":'lange Torque Sheet - 36 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-4-Bolt.docx',"title":'lange Torque Sheet - 4 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-44-Bolt.docx',"title":'lange Torque Sheet - 44 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-lange-Torque-Sheet-8-Bolt.docx',"title":'lange Torque Sheet - 8 Bolt',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-nderground-Piping.docx',"title":'nderground Piping',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-olyethylene-HDPE-Piping.docx',"title":'olyethylene HDPE Piping',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-ose-Reel-Hydrant.docx',"title":'ose Reel & Hydrant',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-pool-Drying-and-Cleaning.docx',"title":'pool Drying and Cleaning',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-ressure-Testing.docx',"title":'ressure Testing',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Piping-uctwork.docx',"title":'uctwork',"cat":'piping',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  # ELECTRICAL
  {"file":'ITR-Electrical-Accommodation-Building-DB-LSP.docx',"title":'Accommodation Building DB LSP',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Accomodation-Building-DB-LSP.docx',"title":'Accomodation Building DB LSP',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Accomodation-Building-LSP.docx',"title":'Accomodation Building LSP',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Air-Conditioner-HVAC.docx',"title":'Air-Conditioner (HVAC)',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Airconditioner-HVAC-Split-System.docx',"title":'Airconditioner (HVAC Split System)',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Area-Lighting-Survey.docx',"title":'Area Lighting Survey',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Batteries-Battery-Charger.docx',"title":'Batteries Battery Charger',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Batteries-and-Battery-Charger.docx',"title":'Batteries and Battery Charger',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Bolted-Connections-Torque-Check.docx',"title":'Bolted Connections - Torque Check',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Bore-Pump.docx',"title":'Bore Pump',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Cable-Drums-On-Drum-Tests.docx',"title":'Cable Drums On Drum Tests',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Cable-HV-Redundant-Removal.docx',"title":'Cable HV Redundant-Removal',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Cable-LV-Removal.docx',"title":'Cable LV Removal',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Cable-Pit.docx',"title":'Cable Pit',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Cable-Supports-Protection.docx',"title":'Cable Supports Protection',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Contact-Resistance-Ductor-Test.docx',"title":'Contact Resistance - Ductor Test',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Control-Panel.docx',"title":'Control Panel',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Control-Panels.docx',"title":'Control Panels',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Control-Panels-Stations.docx',"title":'Control Panels Stations',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Current-Transformer.docx',"title":'Current Transformer',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Decontactors-Large-J-boxes-Field-Isolators.docx',"title":'Decontactors, Large J boxes Field Isolators',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Distribution-Board.docx',"title":'Distribution Board',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-ELV-Cable.docx',"title":'ELV Cable',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Earthing-Earth-Stake-Grid.docx',"title":'Earthing - Earth Stake Grid',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Earthing-MEN-EP-Bonding-Systems.docx',"title":'Earthing - MEN EP Bonding Systems',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Earthing-Step-Touch-and-Reach.docx',"title":'Earthing - Step, Touch and Reach',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Earthing-Cable-Lay-Not-Terminated.docx',"title":'Earthing Cable Lay (Not Terminated)',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-General-Electrical-Devices.docx',"title":'General Electrical Devices',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-General-Electrical-Equipment.docx',"title":'General Electrical Equipment',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Generator.docx',"title":'Generator',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Cable-Lay.docx',"title":'HV Cable Lay',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Function-Protection-Relay.docx',"title":'HV Function Protection Relay',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Incomer-Module-Feeder-Module.docx',"title":'HV Incomer Module, Feeder Module',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Incomer-Feeder-Module-CB.docx',"title":'HV Incomer, Feeder Module CB',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Inline-Joint.docx',"title":'HV Inline Joint',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-MCC-Switchboard.docx',"title":'HV MCC Switchboard',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-MCC-Switchboard.docx',"title":'HV MCC, Switchboard',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Power-Cable.docx',"title":'HV Power Cable',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Protection-Relay.docx',"title":'HV Protection Relay',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-HV-Rotor-Resistance-Cubicle.docx',"title":'HV Rotor Resistance Cubicle',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Heater-Elements.docx',"title":'Heater Elements',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-LV-Cable-Lay.docx',"title":'LV Cable Lay',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-LV-Control-Cable.docx',"title":'LV Control Cable',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-LV-Function-Protection.docx',"title":'LV Function Protection',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-LV-Incomer-Feeder-Module-CB.docx',"title":'LV Incomer, Feeder Module CB',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-LV-Inline-Joint.docx',"title":'LV Inline Joint',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-LV-MCC-Switchboard.docx',"title":'LV MCC, Switchboard',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-LV-Power-Cable.docx',"title":'LV Power Cable',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Lighting-Small-Power.docx',"title":'Lighting Small Power',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Local-Control-Station.docx',"title":'Local Control Station',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Motor-Non-Separable-Coupling.docx',"title":'Motor Non-Separable Coupling',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Motor-Separable-Coupling.docx',"title":'Motor Separable Coupling',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Neutral-Earthing-Resistor.docx',"title":'Neutral Earthing Resistor',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Pole-Top-ABS-Isolator.docx',"title":'Pole Top ABS-Isolator',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Pole-Top-Transformer.docx',"title":'Pole Top Transformer',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Power-Transformer.docx',"title":'Power Transformer',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Power-line-pole.docx',"title":'Power line pole',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Powerline-Conductor.docx',"title":'Powerline Conductor',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Pre-Energisation-Insulation-Continuity-Test.docx',"title":'Pre-Energisation Insulation Continuity Test',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-RMU-Switch.docx',"title":'RMU Switch',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Recloser.docx',"title":'Recloser',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Substation-or-Switchroom-Pre-Energisation.docx',"title":'Substation or Switchroom Pre-Energisation',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Surge-Diverter.docx',"title":'Surge Diverter',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-TX-Oil-Sample.docx',"title":'TX Oil Sample',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Temp-Gen-Installation-Pre-Energisation-Insulation-Continuity-Test.docx',"title":'Temp Gen Installation Pre-Energisation Insulation Continuity Test',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Temp-Gen-Removal-Pre-Energisation-Insulation-Continuity-Test.docx',"title":'Temp Gen Removal Pre-Energisation Insulation Continuity Test',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Trenching-Conduit-Installation.docx',"title":'Trenching Conduit Installation',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-UPS-System.docx',"title":'UPS System',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Variable-Speed-Drive.docx',"title":'Variable Speed Drive',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-Electrical-Voltage-Transformer.docx',"title":'Voltage Transformer',"cat":'electrical',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  # INSTRUMENTATION
  {"file":'ITR-Instrument-Analyser.docx',"title":'Analyser',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Belt-Drift-Switch.docx',"title":'Belt Drift Switch',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Belt-Rip-Switch.docx',"title":'Belt Rip Switch',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Belt-Weigher.docx',"title":'Belt Weigher',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Blocked-Chute-Switch.docx',"title":'Blocked Chute Switch',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Cable.docx',"title":'Cable',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Control-Panel.docx',"title":'Control Panel',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Control-Valve-Motorised-Pneumatic-or-Modulating.docx',"title":'Control Valve (Motorised, Pneumatic or Modulating)',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Encoder.docx',"title":'Encoder',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-General.docx',"title":'General',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-General-Discrete.docx',"title":'General (Discrete)',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Hydraulic-Brake.docx',"title":'Hydraulic Brake',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Hydraulic-Brake-Pack.docx',"title":'Hydraulic Brake Pack',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Indicating-Light-Siren.docx',"title":'Indicating Light Siren',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Instrument-Control-Panel.docx',"title":'Instrument Control Panel',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Instrument-General.docx',"title":'Instrument General',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Instrument-General-Discrete.docx',"title":'Instrument General (Discrete)',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Level-Switch.docx',"title":'Level Switch',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Level-Transmitter.docx',"title":'Level Transmitter',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Marshalling-Panel.docx',"title":'Marshalling Panel',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Metal-Detector.docx',"title":'Metal Detector',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Pre-Install-Calibration.docx',"title":'Pre-Install Calibration',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Pull-Wire-Switch.docx',"title":'Pull Wire Switch',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-RTD.docx',"title":'RTD',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Under-Speed-Switch.docx',"title":'Under Speed Switch',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Instrument-Underspeed-Switch.docx',"title":'Underspeed Switch',"cat":'instrumentation',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  # FIRE_GAS
  {"file":'ITR-FireGas-Activation-Indicating-and-Warning-Device.docx',"title":'Activation, Indicating and Warning Device',"cat":'fire_gas',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-FireGas-Fire-Indication-Panel.docx',"title":'Fire Indication Panel',"cat":'fire_gas',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  {"file":'ITR-FireGas-VESDA-Fire-Indicator-Panel.docx',"title":'VESDA Fire Indicator Panel',"cat":'fire_gas',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality', 'HSE']},
  # TELECOMS
  {"file":'ITR-Telecoms-Access-Control-System.docx',"title":'Access Control System',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Telecoms-CAT-56-Cable.docx',"title":'CAT 56 Cable',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Telecoms-CCTV-Camera.docx',"title":'CCTV Camera',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Telecoms-Comms-CubicleEnclosure.docx',"title":'Comms CubicleEnclosure',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Telecoms-FOBOT.docx',"title":'FOBOT',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Telecoms-FOSE.docx',"title":'FOSE',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Telecoms-Fibre-Optic-Cable.docx',"title":'Fibre Optic Cable',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Telecoms-OPGW-Fibre-Optic-Cable.docx',"title":'OPGW (Fibre Optic Cable)',"cat":'telecoms',"fmt":'docx',"stages":[5, 6],"roles":['Engineer', 'Quality']},
  # ARCHITECTURAL
  {"file":'ITR-Architectural-Accommodation-Building-External.docx',"title":'Accommodation Building External',"cat":'architectural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Architectural-Accommodation-Building-Internal.docx',"title":'Accommodation Building Internal',"cat":'architectural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Architectural-Building-External.docx',"title":'Building External',"cat":'architectural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Architectural-Building-Internal.docx',"title":'Building Internal',"cat":'architectural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Architectural-Deconstruction.docx',"title":'Deconstruction',"cat":'architectural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality']},
  {"file":'ITR-Architectural-Wardrobe-Installation.docx',"title":'Wardrobe Installation',"cat":'architectural',"fmt":'docx',"stages":[5],"roles":['Engineer', 'Quality']},
]
